### ISSUE TITLE
Docker image labels are no longer included

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.pacta#26]
labels are defined in Dockerfile here
https://github.com/RMI-PACTA/workflow.pacta/blob/4abe0210c570d409cc3bc52f71d3b6a9344805a8/Dockerfile#L14-L24

but pushed Docker images in GHCR no longer have a description e.g. https://github.com/RMI-PACTA/workflow.pacta/pkgs/container/workflow.pacta/154024817?tag=nightly

possibly related to the build process doing multi-arch now, and the labels need to be defined in a manifest file?

@AlexAxthelm

**Comment by AlexAxthelm** [comment]
@cjyetman Can you expand on the use-case here? I'm seeing the labels available when I do `docker inspect`, so I cannot replicate. 

```sh
❯ docker pull ghcr.io/rmi-pacta/workflow.pacta:nightly
nightly: Pulling from rmi-pacta/workflow.pacta
...
❯ docker inspect ghcr.io/rmi-pacta/workflow.pacta:nightly
[
...
            "Labels": {
                "org.opencontainers.image.authors": "",
                "org.opencontainers.image.base.name": "",
                "org.opencontainers.image.description": "Docker image to run PACTA",
                "org.opencontainers.image.licenses": "MIT",
                "org.opencontainers.image.ref.name": "",
                "org.opencontainers.image.revision": "",
                "org.opencontainers.image.source": "https://github.com/RMI-PACTA/workflow.pacta",
                "org.opencontainers.image.title": "",
                "org.opencontainers.image.vendor": "",
                "org.opencontainers.image.version": ""
            }
...
]

```

**Comment by cjyetman** [comment]
for instance [here](https://github.com/RMI-PACTA/workflow.pacta/pkgs/container/workflow.pacta/158959152?tag=nightly) it shows...
<img width="816" alt="Screenshot 2023-12-18 at 13 35 43" src="https://github.com/RMI-PACTA/workflow.pacta/assets/1708872/3ce2dbab-7e84-4a57-881d-482352e3dfc6">

but [before](https://github.com/RMI-PACTA/workflow.pacta/pkgs/container/workflow.pacta/148572290?tag=pr11) it would show...
<img width="869" alt="Screenshot 2023-12-18 at 13 37 07" src="https://github.com/RMI-PACTA/workflow.pacta/assets/1708872/3e19b4a6-e922-4c5e-95a6-1d5f5453c386">

also no longer shows this...
<img width="285" alt="Screenshot 2023-12-18 at 13 38 14" src="https://github.com/RMI-PACTA/workflow.pacta/assets/1708872/e61ccf06-98b2-4629-b7c9-2d73de6a2a56">

**Comment by cjyetman** [comment]
and GitHub's documentation about it is here https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#labelling-container-images

**Comment by AlexAxthelm** [comment]
@cjyetman I think we can close this?

This is what I see [here](https://github.com/RMI-PACTA/workflow.pacta/pkgs/container/workflow.pacta/219012209?tag=pr-58):
![Screenshot_2024-05-21_16 09 07](https://github.com/RMI-PACTA/workflow.pacta/assets/2974734/6b2748b4-c09c-4333-bbdd-2eb5dfa6c56f)

**Comment by cjyetman** [comment]
yup, looks like it's picking up these labels again
