### ISSUE TITLE
consider building a linux arm64 image as well as a linux amd64 image

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/workflow.pacta#32]
In #31, I got the buildx multi-aarch process working to build both an amd64 and an arm64 (runs faster on an arm64 Mac because it doesn't have to run in emulation) image, however, the time it takes to compile all the R packages when building the arm64 Docker image (because no one provides pre-built linux arm64 binaries) is long (~45min), and since emulation when running a container on Mac appears to have improved substantially over the past few years, the costs currently seem to outweigh the benefits.

This may be worth checking in on in a few months to see if a CRAN-like repo is offering pre-built linux arm64 binaries, or if there's another way to achieve it that's faster.

the prototype branch is here:
https://github.com/RMI-PACTA/workflow.pacta/tree/cjyetman-patch-1

**Comment by AlexAxthelm** [comment]
This has been closed with #50
