### ISSUE TITLE
Accept multiple input CSVs

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/workflow.pacta#35]
Expected behavior:

* When passing multiple source CSVs in, the config JSON string should include an array of filenames.
* when workflow.pacta recieves an array of input portfolio file names, the contents of those portfolios should be combined and aggregated into a single portfolio before further processing (PACTA treats all the contents as though they are a single portfolio)
* Only one logical portfolio is processed (regardless of how many input files it is made of)

[AB#11685](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/11685)

**Comment by AlexAxthelm** [comment]
CC @cjyetman @jdhoffa for opinions

change in config json would god from:

```json
{
 "portfolio_path": "input_dir/default_portfolio.csv",
}
```

to

```json
{
 "portfolio_path": [
    "input_dir/default_portfolio.csv"
  ],
}
```

or

```json
{
 "portfolio_path": [
    "input_dir/portfolio_1.csv",
    "input_dir/portfolio_2.csv",
    "input_dir/portfolio_3.csv"
  ],
}
```

**Comment by jdhoffa** [comment]
@AlexAxthelm I found this issue when reviewing some [open discussions with Silicon Ally](https://docs.google.com/document/d/17cWg1Ist3hFiwFC6cLBhXbxL7MiEIwsFAM5Iywj_cEk/edit?disco=AAABFzsGm1E), is this still an important update? 

If yes, I'll make sure to get it on the next sprint :-)
