### ISSUE TITLE
Clean up container LABELs (and annotations)

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/workflow.pacta#46]
We currently export a lot of empty strings as Docker labels in our image:
https://github.com/RMI-PACTA/workflow.pacta/blob/77f6ee025d06265e7ab412f01497773f1d812701/Dockerfile#L18-L24

Since these do not add information, we can remove them (or even better, make them non-empty informative strings)

See: https://github.com/opencontainers/image-spec/blob/main/annotations.md for details about the annotations

**Comment by jdhoffa** [comment]
This was added on purpose, to over-write existing labels set in the `rocker` base image (i believe).

A lot of our built images had labels like "Author: Hadley Wickham"

**Comment by jdhoffa** [comment]
See:
https://github.com/RMI-PACTA/workflow.transition.monitor/pull/212

**Comment by AlexAxthelm** [comment]
Hmm. yeah. I see that as I'm trying to sort this out locally. ☹️ 

I'll keep thinking on this.
